[workspace.package]
version = "0.1.0"
edition = "2024"

authors = ["Claudio Carraro <carraro.claudio@gmail.com>"]
repository = "https://github.com/in3hkf/icctl"
description = "Icom radio control using CI-V protocol"
license-file = "LICENSE"


[workspace]
members = ["crates/ci-v"]
resolver = "3"

[workspace.dependencies]
# Dipendenze condivise qui
